# Site settings
title: Magdalena Piątek - Badacz i projektant UX (User Experience)
email: kontakt@magdalena-piatek.pl
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://magdalena-piatek.pl" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

redirects: yes
collections:
    projects:
        output: true
